<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

echo "\n    <div class=\"mainBody\">\n        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12\">\n            <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12 dashboardheaderMain\">\n                <div class=\"row margin\">\n                    <div class=\"col-sm-2 col-xs-2 col-md-2 col-lg-2 padding\">\n                        <div class=\"headerLogo\">\n                            <a class=\"nav-link text-light\" href=\"dashboard.php\" title=\"IPTV Smarters-WebTV\">\n                                <!-- <img src=\"";
echo !empty($logovalue) ? $logovalue : "themes/" . $currenttheme . "/images/iptv-smarter-logo.png";
echo "\" alt=\"IPTV Smarters-WebTV\"> -->\n                                <img src=\"";
echo !empty($logovalue) ? $logovalue : "themes/" . $currenttheme . "/images/logo_home1.png";
echo "\" alt=\"IPTV Smarters-WebTV\">\n                            </a>\n                       </div>\n                    </div>\n                    <div class=\"col-sm-5 col-xs-5 col-md-5 col-lg-5 padding\">\n                        <div class=\"headerTime\">\n                            <span class=\"time\"></span> <span class=\"date\"> ";
echo date("F d, Y");
echo "</span>\n                        </div>\n                    </div>\n                    <div class=\"col-sm-3 col-xs-3 col-md-3 col-lg-3 padding\">\n                        <div class=\"headerSearch\">\n                        <a href=\"mastersearch.php\">\n                            <span>\n                                <i class=\"fa fa-search\" aria-hidden=\"true\"></i>&nbsp; Master Search\n                            </span>\n                        </a>\n                       </div>\n                    </div>\n                    <div class=\"col-sm-2 col-xs-2 col-md-2 col-lg-2 padding\">\n                        <div class=\"col-sm-12\">\n                            <div class=\"headerIcon\">\n                                <div>\n                                    <a href=\"radio.php\">\n                                    <img src=\"themes/";
echo $currenttheme;
echo "/images/radio-icon.png\" class=\"img-icon\">\n                                    </a>\n                                </div>\n                                <div>\n                                    <a href=\"userinfo.php\">\n                                    <img src=\"themes/";
echo $currenttheme;
echo "/images/user-icon.png\" class=\"img-icon\">\n                                    </a>\n                                </div>\n                                <div>\n                                    <a  href=\"settings.php\">\n                                    <img src=\"themes/";
echo $currenttheme;
echo "/images/settings.png\" class=\"img-icon\">\n                                    </a>\n                                </div>\n                                <div>\n                                    <a href=\"switchuser.php\">\n                                    <img src=\"themes/";
echo $currenttheme;
echo "/images/switch-user-icon.png\" class=\"img-icon\">\n                                    </a>\n                                </div>\n                            </div>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12 bodyDiv\"> \n            <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12\">\n                <div class=\"row margin\">\n                    <div class=\"col-sm-4 col-xs-4 col-md-4 col-lg-4 getLiveResponse padding\">\n                        <a href=\"live.php\" class=\"\">\n                            <div class=\"section_img1\">\n                                <span><img src=\"themes/";
echo $currenttheme;
echo "/images/live-tv.png\" class=\"section-logoLive\"></span>\n                                <span class=\"section-title-1\"> Live TV </span>\n                            </div>\n                        </a>\n                    </div>\n                    <div class=\"col-sm-8 col-xs-8 col-md-8 col-lg-8 padding\">\n                        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12 bodyRightDiv\">\n                            <div class=\"row margin\">\n                                <div class=\"col-sm-6 col-xs-6 col-md-6 col-lg-6 getmovieResponse padding\">\n                                    <a href=\"movies.php\">\n                                        <div class=\"section_img2\">\n                                            <span><img src=\"themes/";
echo $currenttheme;
echo "/images/movie-s.png\" class=\"section-logo\"></span>                 \n                                            <span class=\"section-title-2\"> Movies </span>\n                                        </div>\n                                    </a>\n                                </div>\n                                <div class=\"col-sm-6 col-xs-6 col-md-6 col-lg-6 getmovieResponse padding\">\n                                    <a href=\"series.php\">\n                                        <div class=\"section_img3\">\n                                            <span><img src=\"themes/";
echo $currenttheme;
echo "/images/serie-s.png\" class=\"section-logo\"></span> \n                                            <span class=\"section-title-3\"> Series </span>\n                                        </div>\n                                    </a>\n                                </div>\n                            </div>\n                        </div>\n                        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12 bodyBottomRight\">\n                            <div class=\"row margin\">\n                                <div class=\"col-sm-4 col-xs-4 col-md-4 col-lg-4\">\n                                    <a href=\"epg.php\" class=\"btn btn-cus-dash forMob0\">                            \n                                        <span><img src=\"themes/";
echo $currenttheme;
echo "/images/epg2.png\" class=\"sectionstrip-logo\"></span> Live With EPG\n                                    </a>\n                                </div>\n                                <div class=\"col-sm-4 col-xs-4 col-md-4 col-lg-4\">\n                                    <a href=\"catchup.php\" class=\"btn btn-cus-dash forMob1\">                         \n                                        <span><img src=\"themes/";
echo $currenttheme;
echo "/images/catch_up_icon.png\" class=\"sectionstrip-logo\"></span> CatchUp\n                                    </a>\n                                </div>\n                                <div class=\"col-sm-4 col-xs-4 col-md-4 col-lg-4\">\n                                    <button type=\"button\" class=\"btn btn btn-cus-dash logoutBtn forMob2\" data-bs-toggle=\"modal\" data-bs-target=\"#logoutConfirmationbox\">\n                                        <span><img src=\"themes/";
echo $currenttheme;
echo "/images/logout.png\" class=\"sectionstrip-logo\"></span> Logout\n                                    </button>\n                                </div> \n                            </div>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12\">\n            <div class=\"col-12 col-sm-12 col-xs-12 col-md-12 col-lg-12 footerText\">\n                <div class=\"row margin\">\n                    <div class=\"col-4 col-sm-4 col-xs-4 col-md-4 col-lg-4\" style=\" text-align: initial !important; \">\n                        <span> Expiration:  ";
if ($_SESSION["webTvplayer"]["exp_date"] == "null" || $_SESSION["webTvplayer"]["exp_date"] == "") {
    echo "Unlimited";
} else {
    echo date("F d, Y", $_SESSION["webTvplayer"]["exp_date"]);
}
echo "                        </span>\n                    </div>\n                    <div class=\"col-4 col-sm-4 col-xs-4 col-md-4 col-lg-4\"></div>\n                    <div class=\"col-4 col-sm-4 col-xs-4 col-md-4 col-lg-4\" style=\"text-align: end !important;\">\n                        <span class=\"logFooter\"> Logged in: ";
echo $_SESSION["webTvplayer"]["anyname"];
echo "</span>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n    <!-- Modal -->\n    <div class=\"modal fade\" id=\"logoutConfirmationbox\" tabindex=\"-1\" aria-labelledby=\"logoutlable\" aria-hidden=\"true\">\n        <div class=\"modal-dialog\">\n          <div class=\"modal-content\">\n            <div class=\"modal-header\">\n              <h5 class=\"modal-title\" id=\"logoutlable\"> Confirmation </h5>\n              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n            </div>\n            <div class=\"modal-body\">\n                  Are you sure?\n            </div>\n            <div class=\"modal-footer\">\n              <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">No, cancel!</button>\n              <button type=\"button\" class=\"btn btn-primary log_out\">Yes, logout me!</button>\n            </div>\n          </div>\n        </div>\n    </div>\n</body>\n</html>";

?>