<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

echo "<div class=\"mainBody\">\n        <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12\">\n            <div class=\"col-sm-12 col-xs-12 col-md-12 col-lg-12 listuserHeader\">\n                <div class=\"row\">\n                    <div class=\"col-sm-1 col-xs-1 col-md-1 col-lg-1 padding\">\n                        <div class=\"liveInBack\">\n                            <a class=\"nav-link text-light\" href=\"index.php?adduser\" title=\"Back\">\n                                <img src=\"themes/";
echo $currenttheme;
echo "/images/back_arrow.png\" alt=\"Back\">\n                            </a>\n                        </div>\n                    </div>\n                    <div class=\"col-sm-2 col-xs-2 col-md-2 col-lg-2 padding\" style=\"text-align: initial;\">\n                        <div class=\"liveInLogo\">\n                            <a class=\"nav-link text-light\" href=\"index.php?adduser\" title=\"IPTV Smarters-WebTV\">\n                                <img src=\"";
echo !empty($logovalue) ? $logovalue : "themes/" . $currenttheme . "/images/logo_home1.png";
echo "\" alt=\"IPTV Smarters-WebTV\">\n                            </a>\n                       </div>\n                    </div>\n                    <div class=\"col-sm-6 col-xs-6 col-md-6 col-lg-6 padding\">\n                        <div class=\"listuserName text_center\">\n                            <span>LIST USER</span>\n                       </div>\n                    </div>\n                    <div class=\"col-sm-3 col-xs-3 col-md-3 col-lg-3 padding\">\n                            <div class=\"listuserTime\" style=\" text-align: end; \">\n                                <a href=\"index.php?adduser\" style=\" text-decoration: none; color: white;\">\n                                <span> <img src=\"themes/";
echo $currenttheme;
echo "/images/add_more_user.png\" style=\" width: 14%; backdrop-filter: opacity(0.5);\"> &nbsp;&nbsp; <label style=\"cursor: pointer;\">ADD USER</label></span> &nbsp;&nbsp;&nbsp;&nbsp;\n                                </a>\n                       </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div class=\"col-sm-12\">\n            <div class=\"col-sm-12\">\n                <div class=\"row listUserDIV\">\n                </div>\n            </div>\n        </div>\n    </div>\n\n\n\n <div class=\"modal fade\" id=\"confirmdeletelistuser\" tabindex=\"-1\" data-parentsec=\"\" aria-labelledby=\"ListUserModalLabel\" aria-hidden=\"true\">\n        <div class=\"modal-dialog\">\n          <div class=\"modal-content\">\n            <div class=\"modal-header\">\n              <h5 class=\"modal-title\">Confirmation</h5>\n              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n            </div>\n            <div class=\"modal-body\">\n                <p>Are you sure you want to delete <b id=\"usernamehere\" style=\"text-decoration:underline;\"></b> user?</p>\n            </div>\n            <div class=\"modal-footer\">\n                <center>\n                    <button type=\"button\" id=\"confirmdelete\" data-userdelete=\"\" class=\"btn btn-primary\">Confirm</button>\n                    <button type=\"button closeconfirmmodal\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\" aria-label=\"Close\">Close</button>\n                </center>\n            </div>\n          </div>\n        </div>\n    </div>";

?>